## model 
model_name_or_path: Qwen/Qwen3-0.6B
adapter_name_or_path: Experiments/qwen3-0.6B/GSM8K/sft/lora/train
cache_dir: ./.cache
trust_remote_code: true
template: qwen3


### export 
export_dir: models/qwen3-0.6B-GSM8K-lora
export_size: 2
export_device: auto
export_legacy_format: false


### huggingface
export_hub_model_id: mtybilly/qwen3-0.6B-GSM8K-lora
