### model
model_name_or_path: Qwen/Qwen3-0.6B
adapter_name_or_path: outputs/qwen3-0.6b/gsm8k/sft/lora/train
cache_dir: ./.cache
trust_remote_code: true
enable_thinking: true

### accelerator 
flash_attn: fa2
# use_unsloth: true

### method
stage: sft
do_predict: true
# do_eval: true
finetuning_type: lora

### dataset
eval_dataset: gsm8k_eval
dataset_dir: ./data
template: qwen3
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 4

### output
output_dir: outputs/qwen3-0.6b/gsm8k/vanilla/eval
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 8
# compute_accuracy: true
predict_with_generate: true

